### ISSUE TITLE
Cant add kwh sensor to energy tab

### ISSUE THREAD

**Issue by henrikrox** [rospogrigio/daikin_residential#41]
![2021-12-09 13_01_18-](https://user-images.githubusercontent.com/6884716/145392913-c0ef37fe-ca67-4ae1-9efb-f8b9ffb096a6.png)

Cant add the heating pump sensor for cooling / heating to energy devices it isnt listed

**Comment by henrikrox** [comment]
![2021-12-09 13_02_53-Utviklerverktøy - Home Assistant](https://user-images.githubusercontent.com/6884716/145393072-f02aae5a-be41-49fd-aa22-46fdd97d67bd.png)

![2021-12-09 13_03_12-Konfigurasjon - Home Assistant](https://user-images.githubusercontent.com/6884716/145393125-9d73062b-fac6-40fa-b239-b647527591ec.png)

It isnt listed

**Comment by rospogrigio** [comment]
Hi, Energy sensors are being supported right now, you can try them in PR #42 : can you try it and let me know how it works?
Thank you

**Comment by henrikrox** [comment]
> Hi, Energy sensors are being supported right now, you can try them in PR #42 : can you try it and let me know how it works? Thank you

will do, also found out you can do this
```
homeassistant:
  customize_glob:
    sensor.varmepumpe_stue_daily_heat_energy_consumption:
      unit_of_measurement: 'kWh'
      device_class: energy
      state_class: measurement
      last_reset: "1970-01-01T00:00:00+00:00"
```

But will try the PR also
